### ISSUE TITLE
Use CRDs to manage connectors

### ISSUE THREAD

**Issue by simlay** [infinyon/fluvio-connectors#12]
We need to use CRDs to manage the connectors.

The outcome of this will be `fluvio connector start --config ./config.toml` as well as the corresponding `stop`, this will spin up/down a new set of pods for the given config.

**Comment by nicholastmosher** [comment]
It sounds like `fluvio connector start` will send a request to the SC to create some sort of "ConnectorSpec" and manage that through a control loop.
