### ISSUE TITLE
Upgrade CLI to use Clap v3 over StructOpt

### ISSUE THREAD

**Issue by simlay** [infinyon/fluvio-connectors#152]
Looks like all the functionality of [`StructOpt` has been added to Clap](https://github.com/TeXitoi/structopt#maintenance):

> As clap v3 is now out, and the structopt features are integrated into (almost as-is), structopt is now in maintenance mode: no new feature will be added.
> 
> Bugs will be fixed, and documentation improvements will be accepted.

Doesn't look too hard: https://github.com/clap-rs/clap#example

Basically same issue as https://github.com/infinyon/fluvio/issues/2166

**Comment by pinkforest** [comment]
Clap v3 is by CLI WG own words fast moving breaking target - 

I've migrated geiger to clap v3 derive and cargo has migrated to clap v3 app - so far no issues with it but it's still early days 

StructOps on other hand would stay very stable now it's in maintenance mode -

What would we gain feature wise moving to clap v3 in exchange of dealing with _potentially_ breaking changes upstream on multiple connectors?

**Comment by wendyOn** [comment]
As discussed - closing this issue until we find something clap3 offers over structopt for connectors given the cost/cons of adopting it at this stage.

I understand that auto-completion might be useful for running the binary in dev -

But I think removing clap3 would make more sense for connectors and enforce dev to be run via passed yaml only - separate issue?

It would save compile time and binary size in production and the cost of maintaining clap3 and the dependencies it brings.
