### ISSUE TITLE
Slack Sink connector 

### ISSUE THREAD

**Issue by simlay** [infinyon/fluvio-connectors#183]
After looking at https://api.slack.com/web, it looks like the parameters/secrets to the slack connectors will be:
* [`BEARER_TOKEN`](https://api.slack.com/web#authentication)
* chat_room

We should create a `fluvio-slack-models` crate in the workspace in the `rust-connectors/models/slack` (or something). This will be used for smartmodules, slack sink, and slack source.

**Comment by tjtelan** [comment]
Instead of `chat_room`, I think the Slack nomenclature is `channel`

**Comment by wendyOn** [comment]
I'll close this as I would like to start fresh from the use-case before figuring out how to design code under the hood.

**Comment by wendyOn** [comment]
I'll link to this from use-case: TBD
