### ISSUE TITLE
Fix test in fluvio-test in test-connector

### ISSUE THREAD

**Issue by simlay** [infinyon/fluvio-connectors#212]
The [`fluvio-test.bats`](https://github.com/infinyon/fluvio-connectors/blob/54e46395dbb8fc12ff740841ed350daeaa00326c/rust-connectors/utils/test-connector/tests/fluvio-test.bats#L23-L32) test is failing because the `OFFSETS` column from`fluvio partition list` is empty. This might be a bug in fluvio, not fluvio-connectors.

**Comment by morenol** [comment]
`fluvio partition list` now includes SIZE, I think that because of that we should change the column used by `awk`

**Comment by nacardin** [comment]
This can use https://github.com/infinyon/fluvio/issues/2255

**Comment by sehz** [comment]
Since https://github.com/infinyon/fluvio/issues/2255 is no longer issue, this can should be addressed
