### ISSUE TITLE
Rename instances of SmartStream to SmartModule

### ISSUE THREAD

**Issue by simlay** [infinyon/fluvio-connectors#67]

**Comment by nicholastmosher** [comment]
I know that the term `smartstream` appears in `CommonSourceOpt`, with the following fields:

- `smartstream_filter`
- `smartstream_map`
- `smartstream_arraymap`

I can think of two ways to handle this. One is to just rename these to `smartmodule-`, like this:

- `smartmodule_filter`
- `smartmodule_map`
- `smartmodule_arraymap`

Another option is to just remove the prefix:

- `filter`
- `map`
- `arraymap`

I'm happy to make a PR for whichever we decide

**Comment by nicholastmosher** [comment]
After discussion with @ajhunyady, we'd like to go with removing the prefix in order to be consistent with the `fluvio consume` options. So we'll have:

- `--filter`
- `--map`
- `--arraymap`

etc.
