### ISSUE TITLE
Set up Bors

### ISSUE THREAD

**Issue by sehz** [infinyon/fluvio-connectors#73]

**Comment by tjtelan** [comment]
There is already a [bors config](https://github.com/infinyon/fluvio-connectors/blob/main/bors.toml) and the github action has been configured for listening to `staging` and `trying` branches.

I think that this might be on the bors configuration side. I'm not sure they have access to this repo.

**Comment by tjtelan** [comment]
This works now. We've got a `pong` response from Bors. https://github.com/infinyon/fluvio-connectors/pull/65#issuecomment-971961803
