### ISSUE TITLE
Update HTTP Connector with a parameter to include response headers in Record

### ISSUE THREAD

**Issue by nicholastmosher** [infinyon/fluvio-connectors#97]
Currently, the HTTP connector takes only the body of each HTTP response and puts that into the Record. It would be useful to also have access to other HTTP response metadata such as the headers.

We think it'd be useful to add a parameter to the HTTP configurations such as `response-headers: true` that would cause the HTTP connector to include that information in the Record body. When this option is enabled, the Record data should be formatted like this:

```
{
    "headers": [
        "date: ...",
        ...
    ],
    "body": ...
}
```

Where `body` would be a JSON object if the HTTP body is JSON, or a string with the HTTP response body otherwise (e.g. if the response contains HTML, it'd be put into a string).

**Comment by ajhunyady** [comment]
We need this feature to get access to (data) timestamp as WASM module cannot timestamp as this time.

**Comment by sehz** [comment]
We should pass the entire HTTP request and and expect HTTP response from custom module

**Comment by ajhunyady** [comment]
@sehz what do you mean by custom module?

**Comment by pinkforest** [comment]
I've added the full record on #127 

I'll add the json if that is feasible as well?

It's controlled via output_format body (default) | full | json
